# Generated by Django 5.2 on 2026-01-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('PROMO', 'Promo'), ('CONFRONTATION', 'Confrontation'), ('TRAINING', 'Training'), ('SEGMENT', 'Segment'), ('TURN', 'Turn')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('show_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('PLE', 'PLE'), ('SPECIAL', 'Special')], max_length=20)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('airing_date', models.DateField()),
                ('is_filmed', models.BooleanField(default=False)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('youtube_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('SINGLES', 'Singles'), ('TAG', 'Tag Team'), ('TEAM', 'Team'), ('TRIPLE', 'Triple Threat'), ('FATAL_FOUR', 'Fatal Four-Way'), ('HANDICAP', 'Handicap'), ('GAUNTLET', 'Gauntlet'), ('BATTLE_ROYALE', 'Battle Royale'), ('ROYAL_RUMBLE', 'Royal Rumble')], max_length=30)),
                ('stipulation', models.CharField(blank=True, choices=[('HARDCORE', 'Hardcore'), ('OPEN_CHALLENGE', 'Open Challenge'), ('CONFRONTATION', 'Confrontation'), ('BEST_OF_THREE', 'Best of Three'), ('IRONMAN', 'Ironman'), ('LAST_MAN', 'Last Man Standing'), ('SUBMISSION', 'Submission'), ('STREET_FIGHT', 'Street Fight'), ('LADDER', 'Ladder'), ('HELL_CELL', 'Hell in a Cell'), ('TRAINING', 'Training')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.championship')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMPETITOR', 'Competitor'), ('MANAGER', 'Manager'), ('REFEREE', 'Referee'), ('INTERFERENCE', 'Interference')], max_length=20)),
                ('side', models.CharField(choices=[('TEAM_A', 'Team A'), ('TEAM_B', 'Team B'), ('SOLO', 'Solo')], default='SOLO', max_length=10)),
                ('won', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='booking.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_type', models.CharField(choices=[('PINFALL', 'Pinfall'), ('SUBMISSION', 'Submission'), ('COUNTOUT', 'Countout'), ('DQ', 'Disqualification'), ('UNIQUE', 'Unique'), ('NO_FINISH', 'No Finish')], max_length=20)),
                ('is_no_contest', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='booking.match')),
            ],
        ),
    ]
