# Generated by Django 5.2 on 2026-01-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_match_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.show'),
            preserve_default=False,
        ),
    ]
