# Generated by Django 5.2 on 2026-01-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_event_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stipulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='stipulation',
        ),
        migrations.AddField(
            model_name='match',
            name='stipulations',
            field=models.ManyToManyField(blank=True, related_name='matches', to='booking.stipulation'),
        ),
    ]
