# Generated by Django 5.2 on 2026-01-06 09:17

from django.db import migrations

def create_stipulations(apps, schema_editor):
    Stipulation = apps.get_model("booking", "Stipulation")
    default_stipulations = [
        ("HARDCORE", "Hardcore"),
        ("OPEN_CHALLENGE", "Open Challenge"),
        ("CONFRONTATION", "Confrontation"),
        ("BEST_OF_THREE", "Best of Three"),
        ("IRONMAN", "Ironman"),
        ("LAST_MAN", "Last Man Standing"),
        ("SUBMISSION", "Submission"),
        ("STREET_FIGHT", "Street Fight"),
        ("LADDER", "Ladder"),
        ("HELL_CELL", "Hell in a Cell"),
        ("TRAINING", "Training"),
        ("ELIMINATION", "Elimination"),
        ("WAR", "War"),
        ("FURNITURE_SMASH", "Furniture Smash"),
        ("FIRST_BLOOD", "First Blood"),
        ("TAG_ELIMINATION", "Tag Elimination"),
        ("SUMO_CONTEST", "Sumo Contest"),
        ("SHOOT_FIGHT", "Shoot Fight"),
        ("LAST_LAUGH", "Last Laugh"),
    ]
    for code, name in default_stipulations:
        Stipulation.objects.get_or_create(code=code, name=name)

class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_stipulation_remove_match_stipulation_and_more"),  # replace with the last migration file
    ]

    operations = [
        migrations.RunPython(create_stipulations),
    ]