# Generated by Django 5.1.5 on 2026-01-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_seed_stipulations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('PROMO', 'Promo'), ('CONFRONTATION', 'Confrontation'), ('TRAINING', 'Training'), ('SEGMENT', 'Segment'), ('INJURY', 'Injury'), ('TURN', 'Turn')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(blank=True, choices=[('COMPETITOR', 'Competitor'), ('MANAGER', 'Manager'), ('REFEREE', 'Referee'), ('INTERFERENCE', 'Interference')], max_length=20),
        ),
    ]
