# Generated by Django 5.2 on 2026-01-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('eligibility', models.CharField(choices=[('MEN', 'Men Only'), ('WOMEN', 'Women Only'), ('OPEN', 'Men & Women')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('WRESTLER', 'Wrestler'), ('MANAGER', 'Manager'), ('REFEREE', 'Referee'), ('BOOKER', 'Booker')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NA', 'N/A')], max_length=10)),
                ('alignment', models.CharField(choices=[('FACE', 'Face'), ('HEEL', 'Heel'), ('TWEENER', 'Tweener')], max_length=10)),
                ('finisher', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('injured', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group_type', models.CharField(choices=[('TAG', 'Tag Team'), ('STABLE', 'Stable')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('FRIEND', 'Friend'), ('ENEMY', 'Enemy'), ('MANAGER', 'Manager')], max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.character')),
                ('related_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='core.character')),
            ],
            options={
                'unique_together': {('character', 'related_character', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_group', models.CharField(blank=True, max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.group')),
            ],
            options={
                'unique_together': {('group', 'character')},
            },
        ),
    ]
